  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'

  - name: Generate static HTML
    run: |
      python build.py

  - name: Setup Pages
    uses: actions/configure-pages@v5

  - name: Upload Artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: '.'

  - name: Deploy to GitHub Pages
    id: deployment
    uses: actions/deploy-pages@v4
